<?php

namespace AppBundle\Repository\Curso;

use AppBundle\Entity\Curso\Curso;

/**
 * CursoRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CursoRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function totalCursos(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(DISTINCT curso.id) as total')
            ->from(Curso::class, 'curso');
        try{
            return $qb->getQuery()->getSingleScalarResult();
        }catch (\Exception $exception){
            return 0;
        }
    }
}
