<?php

namespace AppBundle\Repository\Materia;

use AppBundle\Entity\Materia\Materia;

/**
 * MateriaRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MateriaRepository extends \Doctrine\ORM\EntityRepository
{

    /**
     * @return mixed
     */
    public function totalMaterias(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(DISTINCT materia.id) as total')
            ->from(Materia::class, 'materia');
        try{
            return $qb->getQuery()->getSingleScalarResult();
        }catch (\Exception $exception){
            return 0;
        }
    }

}
