<?php

namespace AppBundle\Repository\Docente;

use AppBundle\Entity\Docente\Docente;

/**
 * DocenteRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DocenteRepository extends \Doctrine\ORM\EntityRepository
{
    /**
     * @return mixed
     */
    public function totalDocentes(){
        $qb = $this->getEntityManager()->createQueryBuilder();
        $qb->select('COUNT(DISTINCT docente.id) as total')
            ->from(Docente::class, 'docente');
        try{
            return $qb->getQuery()->getSingleScalarResult();
        }catch (\Exception $exception){
            return 0;
        }
    }
}
